version: "3"
services:
   web:
     image: vikranth2/java-mvn-privaterepos:php
     ports:
     - 8001:80
     depends_on:
     - mysql
   mysql:
     image: vikranth2/java-mvn-privaterepos:mysql
     volumes:
     - db_data:/var/lib/mysql
     environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: mydatabase
volumes:
   db_data: {}
